---
- hosts: localhost
  roles:
    - { role: vagrant, plugins: ['landrush']}
    - { role: oh-my-zsh, plugins: "git"}
    - git

  vars_prompt:
    user_name: "what is your name?"
    user_email: "what is your email?"

  vars:
    applications:
      - adium
      - dropbox
      - owncloud
      - skype
      - vagrant-manager

  tasks:
    # Install application with brew cask
    - name: Install applications with cask
      homebrew_cask: name={{ item }} state=present
      with_items: applications

    # git configuration
    - name: global .gitignore
      template: >
        src=templates/git/gitignore.j2
        dest={{ ansible_env.HOME }}/.gitignore_global
    - name: .gitconfig
      template: >
        src=templates/git/gitconfig.j2
        dest={{ ansible_env.HOME }}/.gitconfig
